// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories.Context;



#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20240219120813_SecondCreate")]
    partial class SecondCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApi.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedTime = new DateTime(2024, 2, 19, 15, 8, 12, 685, DateTimeKind.Local).AddTicks(8823),
                            Price = 60.5m,
                            Title = "Hacigoz ve Karivat"
                        },
                        new
                        {
                            Id = 2,
                            CreatedTime = new DateTime(2024, 2, 19, 15, 8, 12, 685, DateTimeKind.Local).AddTicks(8830),
                            Price = 150m,
                            Title = "Tufek, Mikrop ve Celik"
                        },
                        new
                        {
                            Id = 3,
                            CreatedTime = new DateTime(2024, 2, 19, 15, 8, 12, 685, DateTimeKind.Local).AddTicks(8832),
                            Price = 250m,
                            Title = "Devlet"
                        },
                        new
                        {
                            Id = 4,
                            CreatedTime = new DateTime(2024, 2, 19, 15, 8, 12, 685, DateTimeKind.Local).AddTicks(8835),
                            Price = 45m,
                            Title = "Mesnevi"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
